### PR TITLE
fix corrupted go.mod, add -x to travis to help debug it

### PR DESCRIPTION
**Pull request by wsc1**

### CODE REVIEW

**Comment by mewmew** [comment]
When you say corrupted, what do you mean? And what made it corrupt?

**Comment by wsc1** [comment]
> When you say corrupted, what do you mean? And what made it corrupt?

I'm not sure, somehow it said it was indirectly dependent on golang.org/x/mobile even though there are no such imports.

**Comment by mewmew** [comment]
> I'm not sure, somehow it said it was indirectly dependent on golang.org/x/mobile even though there are no such imports.

Interesting, I wonder which package pulls in these dependencies.

**Comment by wsc1** [comment]
no package pulls in the dependency.   maybe I did a go get in the wrong directory, not sure.

but there are certainly no import dependencies of zc on anything other than go std lib as of yet.

**Pull request merged**
